let job_strings = {
    'refreshJobs' : 'refreshJobs',
	'pruneDatabase' : 'pruneDatabase',
	'trimTracker' : 'trimTracker',
    'sendSms' : 'sendSms',
    'closeInventoryProcess' : 'closeInventoryProcess',
    'unsterilizeExpiredCssdItems' : 'unsterilizeExpiredCssdItems',
    'generateIssueRequestForCssdItemsProcess' : 'generateIssueRequestForCssdItemsProcess',
	'generatePdfrequests' : 'generatePdfrequests',
    'generatePreventiveMaintenanceWorkOrders' : 'generatePreventiveMaintenanceWorkOrders',
    'generateAssetAlertEmails' : 'generateAssetAlertEmails',
    'generateHouseKeepingScheduledWorkOrders' : 'generateHouseKeepingScheduledWorkOrders',
	'createAdmissionRoomBills' : 'createAdmissionRoomBills',
	'generateEmailUserReports' : 'generateEmailUserReports',
	'postToGeneralLedger' : 'postToGeneralLedger',
	'opdandvaccinationdone' : 'opdandvaccinationdone',
	'closePharmacyProcess' : 'closePharmacyProcess',
	'sendOfferMails' : 'sendOfferMails',
	'logoutHandler' : 'logoutHandler',	
	'followupSms' : 'followupSms',
	'generateSalary' : 'generateSalary',
	'doctorFollowupSMS' : 'doctorFollowupSMS',
	'syncTally' : 'syncTally',
	'syncAttendance' : 'syncAttendance',
	'raiseAlerts' : 'raiseAlerts',
	'getCosecdata' : 'getCosecdata',
    'fileissueemail' : 'fileissueemail',
    'vehicleexpirydoc' : 'vehicleexpirydoc',
    'fireexpirydoc' : 'fireexpirydoc',
    'healthawaresms' : 'healthawaresms',
    'notreportedOHCemployees' : 'notreportedOHCemployees',
    'ohcfirstaidboxreport' : 'ohcfirstaidboxreport',
    'crmApiRequests' : 'crmApiRequests',
}

export default {job_strings}